config/routes.rb
Rails.application.routes.draw do
  get 'profiles/show'

  devise_for :users, :controllers => { registrations: 'registrations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#index'
  resources :posts do
    resources :comments
    member do
      get 'like'
    end
  end
  get ':user_name', to: 'profiles#show', as: :profile
  get ':user_name/edit', to: 'profiles#edit', as: :edit_profile
  patch ':user_name/edit', to: 'profiles#update', as: :update_profile
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_votable
  validates :image, presence: true
  has_attached_file :image, styles: { medium: "640x200", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  validates :caption, length: {minimum: 3, maximum: 300}
  belongs_to :user
  has_many :comments, dependent: :destroy

end

app/models/user.rb
class User < ApplicationRecord
  acts_as_voter
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :user_name, presence: true, length: { minimum: 4, maximum: 16 }

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_attached_file :avatar, styles: { medium: '152x152#' }
  validates_attachment_content_type :avatar, content_type:
                                               /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set, only: [:show, :edit, :update, :destroy, :like]
  before_action :authenticate_user!
  before_action :owned, only: [:edit, :update, :destroy]

  def index
    @posts = Post.all.order('created_at DESC').page params[:page]
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success]="post created"
      redirect_to posts_path
    else
      flash.now[:error]= "not created"
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash[:success] = "updated"
      redirect_to posts_path(@post)
    else
      flash.now[:error]="not updated"
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  def like
    if @post.liked_by current_user
      respond_to do |format|
        format.html { redirect_to :back }
        format.js
      end
    end
  end





  private

  def post_params
    params.require(:post).permit(:caption, :image)
  end

  def set
    @post = Post.find(params[:id])
  end

  def owned
    unless current_user == @post.user
      flash[:alert] = "not allowed"
      redirect_to root_path
    end
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation, :current_password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def alert_for(flash_type)
    {
        success: 'alert-success',
        error: 'alert-danger',
        alert: 'alert-warning',
        notice: 'laert-info'
    }[flash_type.to_sym]||flash_type.to_s
  end

  def form_image_select(post)
    return image_tag post.image.url(:medium), id: 'image-preview', class: 'img-responsive' if post.image.exists?
  end

  def profile_avatar_select(user)
    return image_tag user.avatar.url(:medium), id: 'image-preview', class: 'img-responsive img-circle profile-image' if user.avatar.exists?
    image_tag 'default-avatar.jpg', id: 'image-preview', class: 'img-responsive img-circle profile-image'
  end

end

app/helpers/posts_helper.rb
module PostsHelper

  def display_likes(post)
    votes = post.votes_for.up.by_type(User)
    return list_likers(votes) if votes.size <= 1
    count_likers(votes)
  end

  def liked_post(post)
    return 'glyphicon-heart' if current_user.voted_for? post
    'glyphicon-heart-empty'
  end


  private
  def list_likers(votes)
    user_names = []
    unless votes.blank?
      votes.voters.each do |voter|
        user_names.push(link_to voter.user_name,
                                profile_path(voter.user_name),
                                class: 'user-name')
      end
      user_names.to_sentence.html_safe + like_plural(votes)
    end
  end

  def count_likers(votes)
    vote_count = votes.size
    vote_count.to_s + ' likes'
  end

  def like_plural(votes)
    return ' like this' if votes.count > 1
    ' likes this'
  end

end

app/views/comments/_comment.html.haml
#comment
  .user-name
    = link_to comment.user.user_name, profile_path(comment.user.user_name)
    .comment-content
      = comment.content
    - if comment.user == current_user
      = link_to post_comment_path(post, comment), method: :delete, remote: true, data: { confirm: "Are you sure?" } do
        %span(class="glyphicon glyphicon-remove delete-comment")

app/views/comments/index.html.haml
= render @comments, post: @post

app/views/layouts/_layout.html.haml
%nav.navbar.navbar-default
  .navbar-container
    .navbar-header
      %button.navbar-toggle.collapsed{"data-target" => "#bs-navbar-collapse-1", "data-toggle" => "collapse", type: "button"}
      %span.sr-only Toggle Navigation
      %span.icon-bar
      %span.icon-bar
    .navbar-brand=link_to "Photails", root_path
    .collapse.navbar-collapse#bs-navbar-collapse-1
    %ul.nav.navbar-nav.navbar-right
      - if user_signed_in?
        %li
          =link_to "New Post", new_post_path
        %li
          =link_to "Logout",destroy_user_session_path, method: :delete
      -else
        %li
          =link_to "Login", new_user_session_path
        %li
          =link_to "Register", new_user_registration_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Photails
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = render 'layouts/layout'
  %body
    %p
      .container
      -flash.each do |name,msg|
        = content_tag :div, msg, class: [:alert, alert_for(name)]
    = yield

app/views/posts/_form.html.haml
.posts-wrapper
  .post
    .post-body
      .image-wrap
        =form_image_select(@post)
        = simple_form_for @post, html: { multipart: true } do |f|
          .row
            .col-md-12.text-center
              = f.error_notification
          .container-fluid
            .form-group.text-center
              %h4 Upload an image (this is required):
              = f.input :image, label: false, input_html: { onChange: 'loadFile(event)'}
            .form-group.text-center
              = f.input :caption, label: false, placeholder: 'Add your caption'
            .form-group.text-center
              = f.button :submit, class: 'btn-success btn-block'

app/views/posts/_likes.html.haml
.likes{id: "likes_#{post.id}"}
  = display_likes post

app/views/posts/_posts.html.haml
-@posts.each do |post|
  = render 'post', post: post

app/views/posts/edit.html.haml
= render 'form'
.text-center.edit_links
  =link_to "Delete Post", post_path(@post), method: :delete, data:{confirm: "Are you sure?"}
  |
  =link_to "Cancel", posts_path

app/views/posts/index.html.haml
%h1 Photails
.posts-wrapper.row
  #posts
    = render 'posts'
#paginator.text-center
  = link_to_next_page @posts, 'LOAD MORE', remote: true, id: 'load_more'

app/views/posts/index.js.erb
$('#posts').append("<%= j(render 'posts')%>");
$('#paginator').html("<%= escape_javascript(link_to_next_page(@posts, 'LOAD MORE', remote: true, id: 'load_more'))%>");
if (!$('#load_more').length) { $('#paginator').remove(); }

app/views/posts/like.js.erb
$("#like_<%= @post.id %>").removeClass('glyphicon-heart-empty').addClass('glyphicon-heart');
$("#likes_<%= @post.id %>").html("<%= j (render partial:'posts/likes', locals: { post: @post} ) %>");

app/views/posts/new.html.haml
=render 'form'

app/views/posts/show.html.haml
= render 'post', post: @post
- if @post.user.id == current_user.id
  .text-center.edit-links
    = link_to "Cancel", posts_path
    |
    = link_to "Edit Post", edit_post_path(@post)
- else
  .text-center.edit-links
    =link_to "Cancel", posts_path

app/views/profiles/edit.html.haml
.posts-wrapper
  .post
    .post-body
      .image-wrap
        = form_for @user, url: {action: "update"}, html: {multipart: true } do |f|
          .row
            .col-md-12
              .form-group.text-center
                %h4 Change your profile image:
                .img-circle
                  = profile_avatar_select(@user)
                = f.file_field :avatar, onChange:'loadFile(event)'
          .row
            .col-md-12
              .form-group.text-center
                %h4 Update your bio:
                = f.text_area :bio, label: false, rows: 4
          .form-group.text-center
            = f.submit "Update Profile", class: 'btn btn-success'